### ISSUE TITLE
Missing link to this repository at the CTAN "novel" page

### ISSUE THREAD

**Issue by quark67** [rallg/novel#1]
For example, for the **pgf/tikz** package when can see at https://ctan.org/pkg/pgf:

* Support  https://tug.org/mailman/listinfo/pgf-tikz
* Bug tracker  https://github.com/pgf-tikz/pgf/issues
* Repository  https://github.com/pgf-tikz/pgf

It would probably be great to adding theses informations (Support, Bug Tracker and Repository) for your package at https://ctan.org/pkg/novel as you don't give an e-mail address in your documentation. Also, these informations can be added in the documentation.

**Comment by rallg** [comment]
Will do that, when I get around to it soon.

The original GitHub repository for novel was discontinued, once I decided
that I probably would never make any more changes. But recently I decided
that some small changes were needed. The current repository is new:
github.com/rallg/novel

The older version waas slightly adapted by a different author, and can be
found at another GitHub user repository. I have not authenticated any
changes there.

- R.A.
